import './jquery'

import 'admin-lte/bower_components/bootstrap/dist/css/bootstrap.min.css'
import 'admin-lte/bower_components/font-awesome/css/font-awesome.min.css'
import 'admin-lte/bower_components/Ionicons/css/ionicons.min.css'
import 'admin-lte/dist/css/AdminLTE.min.css'
import 'admin-lte/dist/css/skins/_all-skins.min.css'
import 'admin-lte/bower_components/morris.js/morris.css'
import 'admin-lte/bower_components/jvectormap/jquery-jvectormap.css'
//import 'admin-lte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.css'
//import 'admin-lte/bower_components/bootstrap-daterangepicker/daterangepicker.css'
import 'admin-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'

import 'admin-lte/bower_components/jquery/dist/jquery'
import 'admin-lte/bower_components/jquery-ui/jquery-ui'
import 'admin-lte/bower_components/bootstrap/dist/js/bootstrap'
//import 'admin-lte/bower_components/raphael/raphael'
//import 'admin-lte/bower_components/morris.js/morris'
import 'admin-lte/bower_components/jquery-sparkline/dist/jquery.sparkline'
import 'admin-lte/plugins/jvectormap/jquery-jvectormap-1.2.2.min'
import 'admin-lte/plugins/jvectormap/jquery-jvectormap-world-mill-en'
import 'admin-lte/bower_components/jquery-knob/dist/jquery.knob.min'
//import 'admin-lte/bower_components/moment/min/moment.min'
//import 'admin-lte/bower_components/bootstrap-daterangepicker/daterangepicker'
//import 'admin-lte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker'
//import 'admin-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'
import 'admin-lte/bower_components/jquery-slimscroll/jquery.slimscroll'
import 'admin-lte/bower_components/fastclick/lib/fastclick'
import 'admin-lte/dist/js/adminlte'

import 'admin-lte/plugins/iCheck/flat/blue.css'

import './custom.css'